import type { Metadata } from "next";
import dynamic from "next/dynamic";

// import Navbar from "@/components/Navbar";
const Navbar = dynamic(() => import("@/components/Navbar"), { ssr: false });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      {children}
    </div>
  );
}
